image: alpine/latest
packages:
    - cargo
    - hut
    - openssl-dev
    - linux-headers
sources:
    - https://git.sr.ht/~csoliver/rust_tui
tasks:
    - build: |
          cd rust_tui
          cargo build --release
    - upload: |
          hut git artifact upload rust_tui/target/release/rust_tui
submitter:
    git.sr.ht:
        enabled: true
        allow-refs:
            - refs/heads/master
            - "refs/tags/*"
